# Generated by Django 3.0.4 on 2020-03-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebooks.Ebook'),
        ),
    ]
