# Generated by Django 3.0.4 on 2020-03-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0003_auto_20200324_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_author',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
